### ISSUE TITLE
Compilation on macOS Sierra fails with "Could not find `easy` in `tokio_core`"

### ISSUE THREAD

**Issue by gsollazzo** [tokio-rs/tokio-minihttp#15]
Hi!
I'm unable to build on macOS 11.12 with rustc 1.13.0 (2c6933acc 2016-11-07). 

## Step to reproduce the problem:

1. git clone https://github.com/tokio-rs/tokio-minihttp.git
2. cd tokio-minihttp
3. cargo build

#### Output:
>Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/tokio-rs/tokio-service`
    Updating git repository `https://github.com/alexcrichton/futures-rs`
error: no matching package for override `futures:0.1.3` found
location searched: https://github.com/alexcrichton/futures-rs
version required: = 0.1.3

4. Edit Cargo.toml to remove the line
>"futures:0.1.3" = { git = "https://github.com/alexcrichton/futures-rs" }

5. cargo build
#### Output:
>Updating git repository `https://github.com/tokio-rs/tokio-proto`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/tokio-rs/tokio-service`
    Updating git repository `https://github.com/tokio-rs/tokio-core`
error: no matching package for override `tokio-core:0.1.0` found
location searched: https://github.com/tokio-rs/tokio-core
version required: = 0.1.0

6. Edit Cargo.toml to remove the line
>"tokio-core:0.1.0" = { git = "https://github.com/tokio-rs/tokio-core" }

7. cargo build
#### Output:
>Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/tokio-rs/tokio-service`
    Updating git repository `https://github.com/tokio-rs/tokio-proto`
    Updating git repository `https://github.com/carllerche/bytes`
   Compiling httparse v1.2.0
   Compiling bitflags v0.4.0
   Compiling log v0.3.6
   Compiling void v1.0.2
   Compiling lazycell v0.4.0
   Compiling scoped-tls v0.1.0
   Compiling take v0.1.0
   Compiling libc v0.2.17
   Compiling byteorder v0.5.3
   Compiling semver v0.1.20
   Compiling smallvec v0.2.1
   Compiling cfg-if v0.1.0
   Compiling winapi-build v0.1.1
   Compiling futures v0.1.6
   Compiling kernel32-sys v0.2.2
   Compiling rand v0.3.15
   Compiling net2 v0.2.26
   Compiling rustc_version v0.1.7
   Compiling nix v0.7.0
   Compiling slab v0.3.0
   Compiling bytes v0.4.0-dev (https://github.com/carllerche/bytes#93c08064)
   Compiling winapi v0.2.8
   Compiling tokio-service v0.1.0 (https://github.com/tokio-rs/tokio-service#4d1c0256)
   Compiling time v0.1.35
   Compiling mio v0.6.1
   Compiling tokio-core v0.1.1
   Compiling tokio-proto v0.1.0 (https://github.com/tokio-rs/tokio-proto#97063d84)
   Compiling tokio-minihttp v0.1.0 (file:///Users/gio/Projects/tokio-minihttp)
error[E0432]: unresolved import `tokio_core::easy::EasyBuf`
 --> src/request.rs:3:24
  |
3 | use tokio_core::easy::{EasyBuf, Decode};
  |                        ^^^^^^^ Could not find `easy` in `tokio_core`
>error[E0432]: unresolved import `tokio_core::easy::Decode`
 --> src/request.rs:3:33
  |
3 | use tokio_core::easy::{EasyBuf, Decode};
  |                                 ^^^^^^ Could not find `easy` in `tokio_core`
>error[E0432]: unresolved import `tokio_core::easy::Encode`
 --> src/response.rs:3:5
  |
3 | use tokio_core::easy::Encode;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `easy` in `tokio_core`
>error[E0432]: unresolved import `tokio_core::easy::EasyFramed`
  --> src/lib.rs:24:5
   |
24 | use tokio_core::easy::EasyFramed;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `easy` in `tokio_core`
>error: cannot continue compilation due to previous error
>error: Could not compile `tokio-minihttp`.
>To learn more, run the command again with --verbose.

How can I proceed?

**Comment by alexcrichton** [comment]
Thanks for the report! We were waiting on some changes to tokio-proto, but everything should be updated now!
