### ISSUE TITLE
reading the request data

### ISSUE THREAD

**Issue by xrmx** [tokio-rs/tokio-minihttp#17]
Hello, rust newbie here. I haven't found a way to read the data from the requested and thus added the following patch. Am i missing something?

```
diff --git a/src/request.rs b/src/request.rs
index a74d022..25cdb85 100644
--- a/src/request.rs
+++ b/src/request.rs
@@ -43,6 +43,10 @@ impl Request {
     fn slice(&self, slice: &Slice) -> &[u8] {
         &self.data.as_slice()[slice.0..slice.1]
     }
+
+    pub fn data(&self) -> &str {
+        str::from_utf8(self.data.as_ref()).unwrap()
+    }
 }
 
 impl fmt::Debug for Request {
```

**Comment by alexcrichton** [comment]
Are you thinking the body of the HTTP request? Right now `self.data` is just the actual HTTP request itself, so you'd just be getting out the same data as the other methods all return

**Comment by xrmx** [comment]
Yeah, thinking about the body of the http request. Thanks for hint about `self.data`. Anyway am i right assuming is best to take a look at hyper instead of poking with minihttp as a foundation for a web api?

**Comment by alexcrichton** [comment]
Ah ok yeah the "mini" part here in this crate is that it doesn't support HTTP bodies (it's a very small crate). For that I'd recommend hyper, yeah, as it correctly supports far more HTTP features than minihttp here.
