### ISSUE TITLE
HTTP2/QUIC plan

### ISSUE THREAD

**Issue by navidnabavi** [tokio-rs/tokio-minihttp#18]
Do you have any plan to add Http2 or QUIC protocol to this code?

**Comment by alexcrichton** [comment]
Thanks for the report! This repository itself won't be growing larger than it already is as it's mainly just a learning ground for Tokio, but I believe there are other upcoming HTTP2 implementations so stay tuned!

**Comment by navidnabavi** [comment]
Thank I think have to do a Try!
