### ISSUE TITLE
Hello-World benchmark

### ISSUE THREAD

**Issue by yaa110** [tokio-rs/tokio-minihttp#29]
I found this repository from [this blog post](http://aturon.github.io/blog/2016/08/11/futures/). There is a benchmark result at the end of that blog post which demonstrates the notable performance of futures. However, I performed a benchmark test to compare [fasthttp](https://github.com/valyala/fasthttp) and [minihttp](https://github.com/tokio-rs/tokio-minihttp):

**minihttp** `cargo run --example hello-world`

**fasthttp**
```go
func fastHTTPHandler(ctx *fasthttp.RequestCtx) {
	fmt.Fprintf(ctx, "Hello World")
}

func main() {
	fasthttp.ListenAndServe(":8080", fastHTTPHandler)
}
```

The test was performed using [wrk](https://github.com/wg/wrk) tools: `wrk -d 10s http://localhost:8080`

and here is the result:
**minihttp**: 
```
Running 10s test @ http://localhost:8080
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   568.17us   44.22us   2.63ms   92.61%
    Req/Sec     8.84k   353.74     9.27k    72.00%
  175785 requests in 10.00s, 17.27MB read
Requests/sec:  17576.79
Transfer/sec:      1.73MB
```

**fasthttp**: 
```
Running 10s test @ http://localhost:8080
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   527.98us    1.68ms  24.07ms   92.74%
    Req/Sec    70.65k     4.19k   79.65k    74.50%
  1407234 requests in 10.01s, 187.89MB read
Requests/sec: 140552.40
Transfer/sec:     18.77MB
```

What is the reason for this big difference in the results? How can I reach the throughput of fasthttp using futures?

**Comment by alexcrichton** [comment]
Thanks for the report! Did you try running the RUst code with optimizations, e.g. passing the `--release` flag to Cargo?

**Comment by yaa110** [comment]
@alexcrichton  Thank you for the help,

 the result of `cargo run --release --example hello-world` is great:

```
Running 10s test @ http://localhost:8080
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    53.65us   29.50us   3.19ms   98.60%
    Req/Sec    92.47k    13.53k  105.36k    81.19%
  1859072 requests in 10.10s, 182.61MB read
Requests/sec: 184068.70
Transfer/sec:     18.08MB
```

**Comment by alexcrichton** [comment]
Ok! In that case I will close.
