### ISSUE TITLE
Setup dependency

### ISSUE THREAD

**Issue by kination** [tokio-rs/tokio-minihttp#35]
Hello~
I'm trying to implement simple web server with this project, but cannot find how to setup dependency in cargo file. I tried to search library in https://crates.io/ but there was no module `tokio-minihttp`.

How could I do?

Thanks.

**Comment by carllerche** [comment]
You should not use this for anything real. It is mostly a demo. You probably want to use hyper instead.

**Comment by kination** [comment]
@carllerche thanks!
