### ISSUE TITLE
Is it possible to combine minihttp with anything else in the same loop?

### ISSUE THREAD

**Issue by tailhook** [tokio-rs/tokio-minihttp#5]
I can't just call `tokio_minihttp::serve` for that because I don't have the access to Core this way. And I can't copy the code from `tokio_minihttp::Server::serve` because there are lots of private stuff.

Am I missing something obvious?

**Comment by carllerche** [comment]
No... minihttp is only example code :) I didn't feel like adding all the details for configuring the reactor that it runs on, etc...
