### ISSUE TITLE
task error

### ISSUE THREAD

**Issue by stalkerg** [tokio-rs/tokio-minihttp#7]
Under high load by siege I have next errors:
ERROR:tokio_proto::server: task error: Connection reset by peer (os error 104)

I suppose we should try read socket again. 

PS my current performance results really bad. sapper on hyper 2x faster

**Comment by alexcrichton** [comment]
Ok, this has been updated with recent tokio-core/tokio-proto changes and I think this is taken care of now. If you still see this though please let me know!
